//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddrewssBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entry
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public System.Guid PhonebookId { get; set; }
    
        public virtual phonebook phonebook { get; set; }
    }
}
